name: 'Prod build'
on:
  push:
    branches:
      - develop
  pull_request:
    branches: [develop, main]
jobs:
  prod_build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: nodejs
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: install deps
        run: npm install

      - name: compile ts
        run: npm run build

      - name: store build
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: dist2
          path: dist2/
          retention-days: 30

